# Generated by Django 4.0.4 on 2022-06-18 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_user', models.IntegerField(default=0)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nacionalidad_empresa', models.CharField(max_length=100)),
                ('fechaingreso_empresa', models.DateField()),
                ('registro_empresa', models.CharField(default='Sin Confirmacion', max_length=50)),
                ('usuario_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa_vehiculo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo_vehiculo', models.CharField(max_length=100)),
                ('marca_vehiculo', models.CharField(max_length=100)),
                ('nacionalidad_vehiculo', models.CharField(max_length=100)),
                ('color_vehiculo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['placa_vehiculo'],
            },
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id_viajero', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_user', models.IntegerField(default=0)),
                ('nombre_viajero', models.CharField(max_length=100)),
                ('apellido_viajero', models.CharField(max_length=100)),
                ('fachanaci_viajero', models.DateField()),
                ('cargo_viajero', models.CharField(default='Sin Cargo', max_length=50)),
                ('nacionalidad_viajero', models.CharField(default='desconocida', max_length=100)),
                ('identificacion_viajero', models.CharField(default='desconocida', max_length=50)),
                ('tipo_identificacion', models.CharField(default='desconocida', max_length=50)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelos.empresa')),
                ('usuario_viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_viajero'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAduanero',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('estado_registro', models.BooleanField()),
                ('anotaciones_registro', models.CharField(max_length=200)),
                ('id_viajero', models.ForeignKey(blank=True, db_column='id_viajero', null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelos.viajero')),
                ('placa_vehiculo', models.ForeignKey(db_column='placa_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='Modelos.vehiculo')),
            ],
            options={
                'ordering': ['id_registro'],
            },
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id_mercancia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mercancia', models.CharField(max_length=100)),
                ('descripcion_mercancia', models.CharField(max_length=100)),
                ('peso_mercancia', models.FloatField()),
                ('precio_mercancia', models.TextField()),
                ('tipo_producto_mercancia', models.CharField(max_length=100)),
                ('clasificacion_mercancia', models.CharField(max_length=100)),
                ('placa_vehiculo', models.ForeignKey(blank=True, db_column='placa_vehiculo', null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelos.vehiculo')),
            ],
            options={
                'ordering': ['id_mercancia'],
            },
        ),
        migrations.CreateModel(
            name='Aduanero',
            fields=[
                ('id_aduanero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aduanero', models.CharField(max_length=100)),
                ('apellido_aduanero', models.CharField(max_length=100)),
                ('tipo_user', models.IntegerField(default=0)),
                ('fachanaci_aduanero', models.DateField()),
                ('cargo_aduanero', models.CharField(max_length=100)),
                ('nacionalidad_aduanero', models.CharField(max_length=100)),
                ('dui_aduanero', models.CharField(max_length=20)),
                ('usuario_aduanero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_aduanero'],
            },
        ),
    ]
