# Generated by Django 4.0.4 on 2022-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaduanero',
            name='reg_registro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registroaduanero',
            name='estado_registro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registroaduanero',
            name='id_registro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
