# Generated by Django 4.0.4 on 2022-06-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_registroaduanero_reg_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaduanero',
            name='placa_vehiculo',
        ),
        migrations.AddField(
            model_name='registroaduanero',
            name='carga_registro',
            field=models.ForeignKey(db_column='id_mercancia', default=0, on_delete=django.db.models.deletion.CASCADE, to='Modelos.mercancia'),
        ),
    ]
