# Generated by Django 4.0.4 on 2022-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_remove_registroaduanero_placa_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='nombre_mercancia',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='peso_mercancia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='precio_mercancia',
            field=models.FloatField(default=0.0),
        ),
    ]
