# Generated by Django 4.0.4 on 2022-06-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_alter_mercancia_nombre_mercancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='id_viajero',
            field=models.ForeignKey(blank=True, db_column='id_viajero', null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelos.viajero'),
        ),
    ]
