# Generated by Django 4.0.4 on 2022-06-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0005_vehiculo_id_viajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa_vehiculo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
